# Generated by Django 4.0.4 on 2022-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=64, unique=True, verbose_name='title')),
                ('episode_nb', models.IntegerField(primary_key=True, serialize=False, verbose_name='episode_nb')),
                ('opening_crawl', models.TextField(null=True, verbose_name='opening_crawl')),
                ('director', models.CharField(max_length=32, verbose_name='director')),
                ('producer', models.CharField(max_length=128, verbose_name='producer')),
                ('release_date', models.DateField(verbose_name='release_date')),
            ],
        ),
    ]
