# Generated by Django 4.0.4 on 2022-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(default='https:://url.ru/'),
            preserve_default=False,
        ),
    ]
