# Generated by Django 4.0.4 on 2022-05-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
