# Generated by Django 4.0.4 on 2022-05-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='photos', upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
