# Generated by Django 4.0.4 on 2022-05-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
